version: "3.8"

services:
    develop:
        build:
            context: .
        tty: true
        volumes:
            - $HOME/workspace/.:/workspace/.
            - $HOME/.aws:/root/.aws
            - $HOME/.zshrc_for_container:/root/.zshrc
            - $HOME/.gitconfig:/root/.gitconfig
            - $HOME/.ssh:/root/.ssh
            - $HOME/.ipython:/root/.ipython
